# Site
name: 'Open|DSE'
description: 'Open Data Science and Engineering Community Website.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'website'
email: 'dse.open@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    vladimir:
      name:           Vladimir Osin 
      site:           https://www.linkedin.com/in/vosin/
      avatar:         /assets/images/team/vladimir_osin.jpg
      bio:            "Data Scientist/Engineer at Signify"

    ekhtiar:
      name:           Ekhtiar Syed
      site:           https://www.linkedin.com/in/ekhtiar/
      avatar:         /assets/images/team/ekhtiar_syed.jpg
      bio:            "Machine Learning Engineer at ASML"

    piero:
      name:           Pierluigi Casale 
      site:           https://www.linkedin.com/in/pierluigicasale/
      avatar:         /assets/images/team/pierluigi_casale.jpg
      bio:            "Group Data Scientist at TomTom"

    damian:
      name:           Damian Andrew Tamburri 
      site:           https://www.linkedin.com/in/maelstrom/
      avatar:         /assets/images/team/damian_andrew_tamburri.jpg
      bio:            "Associate Proffesor at JADS"
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: vladimir
      avatar: /assets/images/team/vladimir_osin.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]